/**
 * Ramsha — Workback Schedule Generator.
 *
 * Generates a list of auto-generated task objects based on key hackathon dates.
 * All dates should be ISO date strings (e.g. "2025-06-15").
 */

function subtractWeeks(dateStr, weeks) {
  const d = new Date(dateStr);
  d.setDate(d.getDate() - weeks * 7);
  return d.toISOString().split("T")[0];
}

let _counter = 0;
function nextId() {
  _counter += 1;
  return `wb-${Date.now()}-${_counter}`;
}

function makeTasks(dueDate, category, titles) {
  return titles.map((title) => ({
    id: nextId(),
    title,
    dueDate,
    category,
    completed: false,
    isAutoGenerated: true,
  }));
}

/**
 * Generate a workback schedule from key hackathon dates.
 *
 * @param {Object} schedule
 * @param {string} schedule.registrationOpen   — ISO date when registration opens
 * @param {string} schedule.registrationClose  — ISO date when registration closes
 * @param {string} schedule.submissionDeadline — ISO date for final submissions
 * @param {string} schedule.judgingStart       — ISO date when judging begins
 * @param {string} schedule.judgingEnd         — ISO date when judging ends
 * @returns {Array<Object>} Array of task objects
 */
function generateWorkbackSchedule(schedule) {
  const {
    registrationOpen,
    registrationClose,
    submissionDeadline,
    judgingStart,
    judgingEnd,
  } = schedule;

  if (!registrationOpen) return [];

  _counter = 0;
  const tasks = [];

  // 4 weeks before registration opens — Planning phase
  const fourWeeksBefore = subtractWeeks(registrationOpen, 4);
  tasks.push(
    ...makeTasks(fourWeeksBefore, "planning", [
      "Set up hackathon platform",
      "Stakeholder meeting",
      "Define goals and success metrics",
      "Invite judges",
    ])
  );

  // 3 weeks before — Outreach phase
  const threeWeeksBefore = subtractWeeks(registrationOpen, 3);
  tasks.push(
    ...makeTasks(threeWeeksBefore, "outreach", [
      "Legal review of rules and terms",
      "First marketing push",
      "Invite sponsors",
    ])
  );

  // 2 weeks before — Content phase
  const twoWeeksBefore = subtractWeeks(registrationOpen, 2);
  tasks.push(
    ...makeTasks(twoWeeksBefore, "content", [
      "Plan workshops and mentorship sessions",
      "Build and review hackathon page",
      "Share page for internal review",
    ])
  );

  // 1 week before — Final prep
  const oneWeekBefore = subtractWeeks(registrationOpen, 1);
  tasks.push(
    ...makeTasks(oneWeekBefore, "preparation", [
      "Schedule all communications",
      "Prepare judging pipeline",
      "Create post-event survey",
    ])
  );

  // Registration opens
  tasks.push(
    ...makeTasks(registrationOpen, "registration", [
      "Send invitations to potential participants",
    ])
  );

  // Registration closes
  if (registrationClose) {
    tasks.push(
      ...makeTasks(registrationClose, "registration", [
        "Finalize accepted teams",
      ])
    );
  }

  // Submission deadline
  if (submissionDeadline) {
    tasks.push(
      ...makeTasks(submissionDeadline, "submissions", [
        "Close submissions",
      ])
    );
  }

  // Judging start
  if (judgingStart) {
    tasks.push(
      ...makeTasks(judgingStart, "judging", [
        "Begin judging period",
      ])
    );
  }

  // Judging end
  if (judgingEnd) {
    tasks.push(
      ...makeTasks(judgingEnd, "judging", [
        "Finalize results",
        "Announce winners",
      ])
    );
  }

  return tasks;
}

module.exports = { generateWorkbackSchedule };
